FROM node:18-alpine AS builder

WORKDIR /app

COPY client/package*.json ./
RUN npm install

COPY client/ ./

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/nginx.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]